### ISSUE TITLE
BigInt.toDouble() calculates incorrectly

### ISSUE THREAD

**Issue by ilikerobots** [a14n/dart-rational#14]
The BigInt toDouble() method is not calculating the nearest double correctly.  Example:
``` expect(BigInt.parse("1").toDouble(), equals(1.0));```
provides 
```  
Expected: <1.0>
  Actual: <2.0>
```

**Comment by a14n** [comment]
Thanks for catching this !

**Comment by a14n** [comment]
fixed by #15

**Comment by a14n** [comment]
version 0.1.9 published
