### ISSUE TITLE
Error in toDecimalString()

### ISSUE THREAD

**Issue by vadimtsushko** [a14n/dart-rational#17]
Hi.

I have certain Rational  value that give me very wrong result for `toDecimalString()`
Example:

```
import 'package:rational/rational.dart';
main() {
  var r = new Rational(2260141353,1042850);
  print(r.toDecimalString());
  print(r.toDouble());
}
```

And output for this is 

```
398.3956902997
2167.2736759840823
```
Second line is OK, first is very strange.

I use hosted version Decimal, rational_dart is on version `0.1.11`
Dart VM version: 2.0.0-dev.35.0 (Fri Mar 9 13:09:14 2018 +0100) on "linux_x64"

**Comment by vadimtsushko** [comment]
I've cloned the repo from github and in that version the error is not reproducible.
So maybe that something about 2.0 SDK with fixed int and old version of library. 
Maybe some warning for current users would help.

**Comment by a14n** [comment]
yes. I made [some changes regarding Dart 2](https://github.com/a14n/dart-rational/compare/v0.1.11...master) but I haven't released a version yet.

**Comment by vadimtsushko** [comment]
Great

**Comment by a14n** [comment]
0.2.0 released
