### ISSUE TITLE
Process hanging in flutter due to simple computating

### ISSUE THREAD

**Issue by wmh** [a14n/dart-rational#19]
The following code runs well in dart, but hanging in flutter. Any idea what the problem is?

```
Rational.parse('91.4906445814007655705') + Rational.parse('0.24047904700217382')
```

My flutter/dart version:

```
Flutter 0.3.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 44b7e7d3f4 (5 weeks ago) • 2018-04-20 01:02:44 -0700
Engine • revision 09d05a3891
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b
```

My Device:

```
[ro.product.model]: [MI 5]
[ro.product.device]: [gemini]
```

**Comment by a14n** [comment]
I can not reproduce the hang with [an up to date master branch of flutter](https://github.com/flutter/flutter/commit/dfc0244e195af93497e2c779c2c0931c579164cf) on an android device. Did you try to test on a simulator ?

**Comment by Aniki312** [comment]
@a14n I can also reproduce the hang with up to date master branch of flutter on my Nexus 5x & Nexus 5. May I know what device you are using?  I could try to find device with same cpu to see if we can reproduce the hang

**Comment by a14n** [comment]
I tested on an old Galaxy S4 (`GT I9505 • 0992383c`).

```dart
import 'package:rational/rational.dart';

void main() {
  print(Rational.parse('91.4906445814007655705') +
      Rational.parse('0.24047904700217382'));
}
```

displays:

```
I/flutter ( 2720): 183462247256805878781/2000000000000000000
```

**Comment by a14n** [comment]
Tested both in release and debug modes on emulators (Nexus 5X/Oreo) and physical devices. Hang still not seen.

Could you test with the simple snippet I pasted in my previous comment?

**Comment by a14n** [comment]
How do you run the test?
- `flutter run`
- `flutter run --release`
- both

**Comment by Aniki312** [comment]
We encounter the hang on a few devices, including Xiaomi Mi 5, hTC a9 , so we are guessing its a issue related to cpu ?

**Comment by a14n** [comment]
I really don't know where the issue is. As you face it with both `flutter run` and `flutter run --release` it looks not related to AOT compilation or VM. And as you face it only on some devices your guess looks valid. Perhaps related to something in the BigInt implementation?

@crelier any idea what it could cause this hang ? Could you take a look please ?

**Comment by Aniki312** [comment]
@a14n 

The hang happen when `Rational.+` is executed
I add some log in rational.dart
 
```
  factory Rational(BigInt numerator, [BigInt denominator]) {
    denominator ??= _INT_1;
    if (denominator == _INT_0) throw new ArgumentError();
    if (numerator == _INT_0) return new Rational._normalized(_INT_0, _INT_1);
    if (denominator < _INT_0) {
      numerator = -numerator;
      denominator = -denominator;
    }
    final aNumerator = numerator.abs();
    final aDenominator = denominator.abs();
    final gcd = _gcd(aNumerator, aDenominator);
    if (gcd == _INT_1) {
      return new Rational._normalized(numerator, denominator);
    } else {
      print("New Rational ");
      print("numerator ${numerator ~/ gcd}");
      print("denominator ${denominator ~/ gcd}");
      return new Rational._normalized(numerator ~/ gcd, denominator ~/ gcd);
    }
  }
```

And here is the output

```
I/flutter (25507): New Rational 
I/flutter (25507): numerator 182981289162801531141
I/flutter (25507): denominator 2000000000000000000
I/flutter (25507): parse a OK
I/flutter (25507): New Rational 
I/flutter (25507): numerator 12023952350108691
I/flutter (25507): denominator 50000000000000000
I/flutter (25507): parse b OK
I/flutter (25507): New Rational 
```
And looks like `~/` operator is what cause the hang on my device.

**Comment by a14n** [comment]
Regarding the log you pasted, a reproduction seems to be:

```dart
void main() {
  var numerator = BigInt.parse('9173112362840293939050000000000000000');
  var gcd = BigInt.parse('50000000000000000');
  print('before');
  var c = numerator ~/ gcd;
  print('after');
}
```
@Aniki312 Could test this snippet please ? Is `after` displayed ?

**Comment by crelier** [comment]
I can indeed reproduce this issue, but it exists only on arm64, and disappears when disabling intrinsics.
I do not see this issue on ia32, x64, or arm.
Can you confirm that you are running on arm64?
Thanks for the report. I'll look into it.

**Comment by crelier** [comment]
A fix in under review: https://dart-review.googlesource.com/c/sdk/+/56740

**Comment by a14n** [comment]
@crelier Awesome, thanks!
