### ISSUE TITLE
Numbers starting with dot should be accepted

### ISSUE THREAD

**Issue by efreibe** [a14n/dart-rational#21]
Hello, I think that numbers with format like .123 should be accepted as a valid number. 
A lot of users are accustomed to write like that in input boxes.

See this example I took from chrome:

![image](https://user-images.githubusercontent.com/1061126/56748353-147b8b00-6756-11e9-9fe7-2791234f82df.png)

Even empty string is returning an exception but this is a valid number zero.

**Comment by a14n** [comment]
Thanks for the report. I agree as it's accepted by `double.parse`.

Fix available in 0.3.4
