### ISSUE TITLE
Do we need to import this package when using Decimal package?

### ISSUE THREAD

**Issue by aytunch** [a14n/dart-rational#35]
`Rational` seems to be already a dependency in `Decimal` package, so in our projects, we should not need to explicitly put rational in our pubspec.yaml
However in our project, importing decimal is not enough to create `Rational`s.
`import 'package:decimal/decimal.dart';`
So you think this is a pub/cache issue on my end?

**Comment by a14n** [comment]
`decimal/decimal.dart` doesn't export `rational.dart` so you have to import `rational/rational.dart` if you want to create a `Rational`.
