### ISSUE TITLE
Is it a better choice to replace BigInt with libgmp via ffi?

### ISSUE THREAD

**Issue by changyiyao** [a14n/dart-rational#38]
In my app(An exchange app), I need make many decimal parsing from string and comparing since I need to resolve the market data of cryptos in a high frequency.

For performance concerns described as the following issues, is it better to wrap libgmp other than be restricted to the issues of BigInt?

https://github.com/dart-lang/sdk/issues/53762
https://github.com/dart-lang/sdk/issues/46180
https://github.com/dart-lang/sdk/issues/46179

**Comment by a14n** [comment]
Unfortunately wrapping libgmp is not possible. It would prevent decimal to be usable on js target.
