### ISSUE TITLE
toStringWithPrecision() should not use toDouble()

### ISSUE THREAD

**Issue by stevenroose** [a14n/dart-rational#7]
`toStringWithPrecision()` uses `toDouble()` to first create a `double` type of the object. This means that very large numbers can be represented incorrectly using this method.

It should be possible to create a fully correct fixed-precision string using the internal numerator and denominator.

**Comment by davidfaulks** [comment]
Thank you, a14n, for fixing this.

**Comment by a14n** [comment]
Fixed via #20
